version: '3.8'

services:
  server:
    build: ./server
    container_name: e-portfolio-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_TO=${EMAIL_TO}
    expose:
      - "5000"
    networks:
      - webnet
    env_file:
      - .env

  client:
    build: ./client
    container_name: e-portfolio-client
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: e-portfolio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/server.crt:/etc/nginx/server.crt:ro
      - ./nginx/certs/server.key:/etc/nginx/server.key:ro
    depends_on:
      - server
      - client
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
